
## Annexe B: erferfrefref {#annexe-b}

## summary stats and features.stats for Gene 

                                         nUnmapped      114628761
                                        nNoFeature       20579292
                                     nAmbigFeature      934096737
                             nAmbigFeatureMultimap      934096737
                                          nTooMany              0
                                     nNoExactMatch         124864
                                       nExactMatch     4458742628
                                            nMatch      964094047
                                      nMatchUnique       30022209
                                     nCellBarcodes         689818
                                             nUMIs       29709734



Number of Reads,1284475633
Reads With Valid Barcodes,0.85576
Sequencing Saturation,0.0104081
Q30 Bases in CB+UMI,0.955089
Q30 Bases in RNA read,0.957923
Reads Mapped to Genome: Unique+Multiple,0.895694
Reads Mapped to Genome: Unique,0.0363836
Reads Mapped to Gene: Unique+Multipe Gene,0.750574
Reads Mapped to Gene: Unique Gene,0.0233731
Estimated Number of Cells,27268
Unique Reads in Cells Mapped to Gene,11121465
Fraction of Unique Reads in Cells,0.370441
Mean Reads per Cell,407
Median Reads per Cell,331
UMIs in Cells,10998607
Mean UMI per Cell,403
Median UMI per Cell,327
Mean Gene per Cell,253
Median Gene per Cell,221
Total Gene Detected,5894


## warning 
!!!!! WARNING: while processing sjdbGTFfile=/projects/microsplit/data/processed_data/STARsolo_result/merged_trimmed/merged/raw_data/genome_annotation/genome_annotation_PsR401_fixed.gtf, line:
CP125962.1	Genbank	exon	298557	300953	.	-	0	transcript_id "gene-QLH64_29550"; gene_id "gene-QLH64_29550"; gene_name "QLH64_29550";
 exon end = 300953 is larger than the chromosome CP125962.1 length = 299955 , will skip this exon




Log of the STARsolo run : 
Alignment statistics:
-----------------------
                          Number of input reads |	1284475633
                      Average input read length |	135
                   Uniquely mapped reads number |	46733841
                        Uniquely mapped reads % |	3.64%
        Number of reads mapped to multiple loci |	1103762730
             % of reads mapped to multiple loci |	85.93%
                Number of reads unmapped: other |	128049614
                     % of reads unmapped: other |	9.97%
                      Mismatch rate per base, % |	0.38%
Fri May 30 15:39:42 CEST 2025 - Pipeline completed!









### Pretest STARSolo on BC_0077  without trimming :

                                        nNoAdapter              0
                                            nNoUMI              0
                                             nNoCB              0
                                            nNinCB              0
                                           nNinUMI        4467771
                                   nUMIhomopolymer        4325324
                                          nTooMany              0
                                          nNoMatch       66837523
                               nMismatchesInMultCB        1680783
                                       nExactMatch      234544811
                                    nMismatchOneWL       13639378
                                 nMismatchToMultWL              0
barcodes stats


#### Genfull summary stats 






| Metric                | Count         |
|-----------------------|---------------|
| nUnmapped            | 89,425,075    |
| nNoFeature           | 1,000,851     |
| nAmbigFeature        | 152,909,678   |
| nAmbigFeatureMultimap| 152,443,034   |
| nTooMany             | 0             |
| nNoExactMatch        | 185,805       |
| nExactMatch          | 729,180,878   |
| nMatch               | 157,719,964   |
| nMatchUnique         | 4,847,425     |
| nCellBarcodes        | 168,346       |
| nUMIs                | 305,287       |

| Metric                                    | Value         |
|------------------------------------------|---------------|
| Number of Reads                           | 325,495,590   |
| Reads With Valid Barcodes                 | 76.19%        |
| Sequencing Saturation                     | 93.70%        |
| Q30 Bases in CB+UMI                       | 92.28%        |
| Q30 Bases in RNA read                     | 86.19%        |
| Reads Mapped to Genome: Unique+Multiple   | 58.16%        |
| Reads Mapped to Genome: Unique            | 2.15%         |
| Reads Mapped to GeneFull: Unique+Multiple | 48.46%        |
| Reads Mapped to GeneFull: Unique          | 1.49%         |
| Estimated Number of Cells                 | 66,026        |
| Unique Reads in Cells Mapped to GeneFull  | 3,538,648     |
| Fraction of Unique Reads in Cells         | 73.00%        |
| Mean Reads per Cell                       | 53            |
| Median Reads per Cell                     | 36            |
| UMIs in Cells                             | 202,967       |
| Mean UMI per Cell                         | 3             |
| Median UMI per Cell                       | 2             |
| Mean GeneFull per Cell                    | 2             |
| Median GeneFull per Cell                  | 2             |
| Total GeneFull Detected                   | 5,295         |





#### Gene summary stats 


                                         nUnmapped       89425075
                                        nNoFeature        7350074
                                     nAmbigFeature      147588031
                             nAmbigFeatureMultimap      147588029
                                          nTooMany              0
                                     nNoExactMatch         182600
                                       nExactMatch      704353731
                                            nMatch      151371640
                                      nMatchUnique        3820029
                                     nCellBarcodes         135433
                                             nUMIs         224743

248001599.933

Number of Reads,325495590
Reads With Valid Barcodes,0.76192
Sequencing Saturation,0.941167
Q30 Bases in CB+UMI,0.922758
Q30 Bases in RNA read,0.861863
Reads Mapped to Genome: Unique+Multiple,0.581583
Reads Mapped to Genome: Unique,0.0215405
Reads Mapped to Gene: Unique+Multipe Gene,0.46505
Reads Mapped to Gene: Unique Gene,0.011736
Estimated Number of Cells,47264
Unique Reads in Cells Mapped to Gene,2582244
Fraction of Unique Reads in Cells,0.675975
Mean Reads per Cell,54
Median Reads per Cell,40
UMIs in Cells,136574
Mean UMI per Cell,2
Median UMI per Cell,2
Mean Gene per Cell,2
Median Gene per Cell,2
Total Gene Detected,4838
