name: Render and Publish Quarto Book

on:
  push:
    branches:
      - main  # Exécute seulement sur la branche principale

# Permissions nécessaires pour le déploiement
permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Quarto installation
        id: cache-quarto
        uses: actions/cache@v4
        with:
          path: ~/quarto
          key: quarto-${{ runner.os }}-1.4.0

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.549  # Version stable spécifique

      - name: Cache TinyTeX
        id: cache-tinytex
        uses: actions/cache@v4
        with:
          path: ~/.TinyTeX
          key: tinytex-${{ runner.os }}-${{ hashFiles('**/*.tex') }}

      - name: Install TinyTeX
        if: steps.cache-tinytex.outputs.cache-hit != 'true'
        run: quarto install tinytex

      - name: Render Quarto Book
        run: |
          quarto check
          quarto render --execute --debug

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs  # Dossier configuré dans _quarto.yml
          force_orphan: true  # Garde uniquement la dernière version de la documentation