name: Render and Publish Quarto Book

on:
  push:
    branches:
      - main  # Exécute seulement sur la branche principale

# Permissions nécessaires pour le déploiement
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rocker/verse:4.3.2
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache Docker images
      - name: Cache Docker images
        uses: actions/cache@v4
        with:
          path: /var/lib/docker
          key: docker-${{ runner.os }}-${{ hashFiles('.github/workflows/publish.yml') }}
          restore-keys: |
            docker-${{ runner.os }}-

      # Cache R packages
      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/R/site-library
          key: r-pkg-${{ runner.os }}-4.3.2-${{ hashFiles('**/*.R', '**/*.Rmd', '**/*.qmd') }}
          restore-keys: |
            r-pkg-${{ runner.os }}-4.3.2-
            r-pkg-${{ runner.os }}-

      # Cache Quarto
      - name: Cache Quarto
        uses: actions/cache@v4
        with:
          path: |
            /opt/quarto
            ~/.local/share/quarto
          key: quarto-${{ runner.os }}-1.4.549-${{ hashFiles('**/*.qmd') }}
          restore-keys: |
            quarto-${{ runner.os }}-1.4.549-
            quarto-${{ runner.os }}-

      # Cache TinyTeX avec une meilleure stratégie
      - name: Cache TinyTeX
        uses: actions/cache@v4
        with:
          path: |
            ~/.TinyTeX
            ~/.cache/tinytex
          key: tinytex-${{ runner.os }}-${{ hashFiles('**/*.tex', '**/*.qmd') }}-${{ github.sha }}
          restore-keys: |
            tinytex-${{ runner.os }}-${{ hashFiles('**/*.tex', '**/*.qmd') }}-
            tinytex-${{ runner.os }}-

      - name: Install System Dependencies
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
          curl \
          gdebi-core \
          && rm -rf /var/lib/apt/lists/*

      - name: Install Quarto
        run: |
          QUARTO_VERSION="1.4.549"
          if [ ! -f "/opt/quarto/bin/quarto" ]; then
            curl -LO "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb"
            gdebi --non-interactive quarto-${QUARTO_VERSION}-linux-amd64.deb
            rm quarto-${QUARTO_VERSION}-linux-amd64.deb
          fi
          quarto --version

      - name: Install R Dependencies
        run: |
          # Create a list of required packages
          required_packages <- c("rmarkdown", "knitr", "tidyverse", "devtools")
          
          # Check installed versions
          installed_packages <- rownames(installed.packages())
          
          # Install missing packages
          missing_packages <- setdiff(required_packages, installed_packages)
          if (length(missing_packages) > 0) {
            install.packages(missing_packages, repos = "https://cloud.r-project.org")
          }
          
          # Print package versions for debugging
          installed.packages()[required_packages, "Version"]
        shell: Rscript {0}

      - name: Install and Configure TinyTeX
        run: |
          if [ ! -d "~/.TinyTeX" ]; then
            # Installation minimale de TinyTeX
            quarto install tinytex --no-prompt
            
            # Préinstaller les packages LaTeX les plus courants
            tlmgr update --self
            tlmgr install \
              amsmath \
              babel-french \
              caption \
              graphics \
              hyperref \
              latex-bin \
              listings \
              lm-math \
              memoir \
              microtype \
              parskip \
              pdftexcmds \
              xcolor \
              fvextra \
              bera \
              mathdesign \
              sourcecodepro \
              fira \
              fontawesome \
              upquote \
              lineno \
              fancyvrb \
              framed \
              booktabs \
              multirow \
              wrapfig \
              float \
              colortbl \
              pdflscape \
              tabu \
              varwidth \
              threeparttable \
              threeparttablex \
              environ \
              trimspaces \
              ulem \
              makecell \
              footnotehyper
              
            # Mettre à jour la base de données
            tlmgr path add
          fi
          
          # Vérifier l'installation
          tlmgr list --only-installed

      # Configuration de pdflatex pour éviter les installations automatiques
      - name: Configure pdflatex
        run: |
          mkdir -p ~/.texmf/web2c
          echo "shell_escape = t" >> ~/.texmf/web2c/texmf.cnf
          echo "auto_install = 0" >> ~/.texmf/web2c/texmf.cnf
          
      - name: Render Quarto Book
        run: |
          quarto check
          TEXMFVAR=~/.texmf quarto render --execute --debug

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4